In [141]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

# Create a dataset

In [142]:
data = make_classification(n_samples = 10, n_features = 2, n_informative = 2, n_redundant = 0, n_classes = 2, random_state =42)

In [143]:
type(data)

tuple

In [144]:
len(data)

2

In [145]:
data

(array([[ 1.06833894, -0.97007347],
        [-1.14021544, -0.83879234],
        [-2.8953973 ,  1.97686236],
        [-0.72063436, -0.96059253],
        [-1.96287438, -0.99225135],
        [-0.9382051 , -0.54304815],
        [ 1.72725924, -1.18582677],
        [ 1.77736657,  1.51157598],
        [ 1.89969252,  0.83444483],
        [-0.58723065, -1.97171753]]),
 array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]))

# Performing Tuple Unpacking

## Extracting Features

In [146]:
X = data[0]

In [147]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [148]:
type(X)

numpy.ndarray

In [149]:
X.shape

(10, 2)

## Extracting Labels

In [150]:
y = data[1]

In [151]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

# Performing a train test split

In [152]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [153]:
X_train.shape

(8, 2)

# Performing MinMax Scaling (range = (0,1), i.e Data Normalization)

In [154]:
from sklearn.preprocessing import MinMaxScaler

In [155]:
sc = MinMaxScaler()

In [156]:
#help(MinMaxScaler)

## fit and transform to training data

In [157]:
sc.fit(X_train)  # fit computes the minimum (X_min) and maximum  (X_max) to be used for later scaling.

MinMaxScaler()

In [158]:
X_train_Scaled = sc.transform(X_train) # Scaling the data according to maximum and minumum value

In [159]:
X_train_Scaled

array([[0.41885108, 0.36181853],
       [0.84826376, 0.25367198],
       [1.        , 0.88216362],
       [0.        , 1.        ],
       [0.49396176, 0.        ],
       [0.1995656 , 0.2480553 ],
       [0.46541255, 0.25607308],
       [0.98927673, 0.19903124]])

In [160]:
X_train_Scaled.max()

1.0000000000000002

In [161]:
X_train_Scaled.min()

0.0

## Using fit_transform in a single line of code

In [162]:
X_train_Scaled_2 = sc.fit_transform(X_train)

In [163]:
X_train_Scaled_2

array([[0.41885108, 0.36181853],
       [0.84826376, 0.25367198],
       [1.        , 0.88216362],
       [0.        , 1.        ],
       [0.49396176, 0.        ],
       [0.1995656 , 0.2480553 ],
       [0.46541255, 0.25607308],
       [0.98927673, 0.19903124]])

# transforming testing data

In [164]:
X_test_Scaled = sc.transform(X_test)

In [165]:
X_test_Scaled

array([[1.0261785 , 0.71067636],
       [0.37561963, 0.28691966]])

# Performing MInMax Scaling ( range  = (-1, 1))

In [166]:
sc2 = MinMaxScaler( feature_range=(-1, 1) )

In [167]:
X_train_new = sc2.fit_transform(X_train)

In [168]:
X_train_new

array([[-0.16229784, -0.27636293],
       [ 0.69652751, -0.49265605],
       [ 1.        ,  0.76432723],
       [-1.        ,  1.        ],
       [-0.01207648, -1.        ],
       [-0.6008688 , -0.50388939],
       [-0.0691749 , -0.48785385],
       [ 0.97855345, -0.60193751]])

In [169]:
X_train_new.max()

1.0000000000000004

In [170]:
X_train_new.min()

-1.0

In [171]:
X_test_new = sc2.transform(X_test)

In [172]:
X_test_new

array([[ 1.052357  ,  0.42135271],
       [-0.24876073, -0.42616069]])